const CircuitActionTypes = {
  FETCH_CIRCUITS: 'FETCH_CIRCUITS',
  CHANGE_PRESSED_CIRCUIT: 'CHANGE_PRESSED_CIRCUIT',
  FIND_PRESSED_CIRCUIT: 'FIND_PRESSED_CIRCUIT',
  INCREMENT_CURRENT_CIRCUIT: 'INCREMENT_CURRENT_CIRCUIT',
  RESET_CURRENT_CIRCUIT: 'RESET_CURRENT_CIRCUIT',
};

export default CircuitActionTypes;
