const AudioActionTypes = {
  TOGGLE_STOP: 'TOGGLE_STOP',
  TOGGLE_START: 'TOGGLE_START',
  TOGGLE_PAUSE_PLAY_STOP: 'TOGGLE_PAUSE_PLAY_STOP',
  TOGGLE_PAUSE_PLAY_START: 'TOGGLE_PAUSE_PLAY_START',
};

export default AudioActionTypes;
