const TimerActionTypes = {
  TOGGLE_TIMER: "TOGGLE_TIMER",
  TOGGLE_TIMER_COLOR: "TOGGLE_TIMER_COLOR",
  RESET_TO_INITIAL_STATE: "RESET_TO_INITIAL_STATE",
  TOGGLE_BUTTON_TITLE: "TOGGLE_BUTTON_TITLE"
};

export default TimerActionTypes;
